//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chempoint.GP.SO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chempoint.GP.SO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string crmServiceConfigurationURL {
            get {
                return ResourceManager.GetString("crmServiceConfigurationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Delete {
            get {
                object obj = ResourceManager.GetObject("Field_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Edit {
            get {
                object obj = ResourceManager.GetObject("Field_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Expansion {
            get {
                object obj = ResourceManager.GetObject("Field_Expansion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Lookup {
            get {
                object obj = ResourceManager.GetObject("Field_Lookup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_MapPoint {
            get {
                object obj = ResourceManager.GetObject("Field_MapPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_NoteAbsent {
            get {
                object obj = ResourceManager.GetObject("Field_NoteAbsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_NotePresent {
            get {
                object obj = ResourceManager.GetObject("Field_NotePresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabricam.
        /// </summary>
        internal static string GP_LICENCE_COMPANY {
            get {
                return ResourceManager.GetString("GP_LICENCE_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE=.
        /// </summary>
        internal static string GP_LICENCE_DBNAME_STR {
            get {
                return ResourceManager.GetString("GP_LICENCE_DBNAME_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i52C5VV289487ALZY|11^276&apos;275q712=85k~.
        /// </summary>
        internal static string GP_LICENCE_KEY {
            get {
                return ResourceManager.GetString("GP_LICENCE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpImage {
            get {
                object obj = ResourceManager.GetObject("HelpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGISTICS.
        /// </summary>
        internal static string SHIPMTHD_LOGISTICS {
            get {
                return ResourceManager.GetString("SHIPMTHD_LOGISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comservice.
        /// </summary>
        internal static string SQL_LOGIN_AUDITOR_PWD {
            get {
                return ResourceManager.GetString("SQL_LOGIN_AUDITOR_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comservice.
        /// </summary>
        internal static string SQL_LOGIN_AUDITOR_USER {
            get {
                return ResourceManager.GetString("SQL_LOGIN_AUDITOR_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpservice.
        /// </summary>
        internal static string SQL_LOGIN_VOID_PWD {
            get {
                return ResourceManager.GetString("SQL_LOGIN_VOID_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGIUM BKORD.
        /// </summary>
        internal static string STR_BELGIUMBKORD {
            get {
                return ResourceManager.GetString("STR_BELGIUMBKORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGIUM INV.
        /// </summary>
        internal static string STR_BELGIUMINV {
            get {
                return ResourceManager.GetString("STR_BELGIUMINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGIUM ORD.
        /// </summary>
        internal static string STR_BELGIUMORD {
            get {
                return ResourceManager.GetString("STR_BELGIUMORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billiing.
        /// </summary>
        internal static string STR_BillToAddressID {
            get {
                return ResourceManager.GetString("STR_BillToAddressID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarrierInstructionID.
        /// </summary>
        internal static string STR_CarrierInstructionID {
            get {
                return ResourceManager.GetString("STR_CarrierInstructionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string STR_CCBE {
            get {
                return ResourceManager.GetString("STR_CCBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        internal static string STR_CCES {
            get {
                return ResourceManager.GetString("STR_CCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string STR_CCGB {
            get {
                return ResourceManager.GetString("STR_CCGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string STR_CCIT {
            get {
                return ResourceManager.GetString("STR_CCIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string STR_CCNL {
            get {
                return ResourceManager.GetString("STR_CCNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHMPT.
        /// </summary>
        internal static string STR_CHMPT {
            get {
                return ResourceManager.GetString("STR_CHMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS.
        /// </summary>
        internal static string STR_CountryNetherlands {
            get {
                return ResourceManager.GetString("STR_CountryNetherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string STR_CountryNL {
            get {
                return ResourceManager.GetString("STR_CountryNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string STR_CountrySpain {
            get {
                return ResourceManager.GetString("STR_CountrySpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE NETHERLANDS.
        /// </summary>
        internal static string STR_CountryTheNetherlands {
            get {
                return ResourceManager.GetString("STR_CountryTheNetherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string STR_CountyBE {
            get {
                return ResourceManager.GetString("STR_CountyBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string STR_CountyBelgium {
            get {
                return ResourceManager.GetString("STR_CountyBelgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        internal static string STR_CountyES {
            get {
                return ResourceManager.GetString("STR_CountyES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string STR_CountyGB {
            get {
                return ResourceManager.GetString("STR_CountyGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string STR_CountyIT {
            get {
                return ResourceManager.GetString("STR_CountyIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string STR_CountyItaly {
            get {
                return ResourceManager.GetString("STR_CountyItaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string STR_CountyUK {
            get {
                return ResourceManager.GetString("STR_CountyUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPEUR.
        /// </summary>
        internal static string STR_CPEUR {
            get {
                return ResourceManager.GetString("STR_CPEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Issues.
        /// </summary>
        internal static string STR_CURRENCYISSUES {
            get {
                return ResourceManager.GetString("STR_CURRENCYISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1900/01/01.
        /// </summary>
        internal static string STR_DATE {
            get {
                return ResourceManager.GetString("STR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics GP.
        /// </summary>
        internal static string STR_DynamicsGP {
            get {
                return ResourceManager.GetString("STR_DynamicsGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAIN BKORD.
        /// </summary>
        internal static string STR_ESBKORD {
            get {
                return ResourceManager.GetString("STR_ESBKORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAIN INV.
        /// </summary>
        internal static string STR_ESINV {
            get {
                return ResourceManager.GetString("STR_ESINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAIN ORD.
        /// </summary>
        internal static string STR_ESORD {
            get {
                return ResourceManager.GetString("STR_ESORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalDestination.
        /// </summary>
        internal static string STR_FinalAddressID {
            get {
                return ResourceManager.GetString("STR_FinalAddressID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalDestination.
        /// </summary>
        internal static string STR_FinalAddressID1 {
            get {
                return ResourceManager.GetString("STR_FinalAddressID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropShip RecFixed=.
        /// </summary>
        internal static string STR_FIXED_DROPSHIP {
            get {
                return ResourceManager.GetString("STR_FIXED_DROPSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB BKORD.
        /// </summary>
        internal static string STR_GBBKORD {
            get {
                return ResourceManager.GetString("STR_GBBKORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB INV.
        /// </summary>
        internal static string STR_GBINV {
            get {
                return ResourceManager.GetString("STR_GBINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB ORD.
        /// </summary>
        internal static string STR_GBORD {
            get {
                return ResourceManager.GetString("STR_GBORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated -.
        /// </summary>
        internal static string STR_GENERATED {
            get {
                return ResourceManager.GetString("STR_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalInstructionID.
        /// </summary>
        internal static string STR_InternalInstructionID {
            get {
                return ResourceManager.GetString("STR_InternalInstructionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 390664.
        /// </summary>
        internal static string STR_ITALY_LOC_CODE {
            get {
                return ResourceManager.GetString("STR_ITALY_LOC_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY BACKORD.
        /// </summary>
        internal static string STR_ITALYBKORD {
            get {
                return ResourceManager.GetString("STR_ITALYBKORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY INV.
        /// </summary>
        internal static string STR_ITALYINV {
            get {
                return ResourceManager.GetString("STR_ITALYINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY ORD.
        /// </summary>
        internal static string STR_ITALYORD {
            get {
                return ResourceManager.GetString("STR_ITALYORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics GP.
        /// </summary>
        internal static string STR_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics GP.
        /// </summary>
        internal static string STR_MESSAGE_TITLE1 {
            get {
                return ResourceManager.GetString("STR_MESSAGE_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select correct Bill To Address from sales customer detail entry window.
        /// </summary>
        internal static string STR_MESSAGE_XRM_BILL_ADDRESS {
            get {
                return ResourceManager.GetString("STR_MESSAGE_XRM_BILL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select correct Ship To Address from sales customer detail entry window.
        /// </summary>
        internal static string STR_MESSAGE_XRM_SHIP_ADDRESS {
            get {
                return ResourceManager.GetString("STR_MESSAGE_XRM_SHIP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNo moved=.
        /// </summary>
        internal static string STR_Moved_AccountNumberIssue {
            get {
                return ResourceManager.GetString("STR_Moved_AccountNumberIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocAmt moved=.
        /// </summary>
        internal static string STR_Moved_DocumentAmountIssue {
            get {
                return ResourceManager.GetString("STR_Moved_DocumentAmountIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCost moved=.
        /// </summary>
        internal static string STR_Moved_DropshipIssue {
            get {
                return ResourceManager.GetString("STR_Moved_DropshipIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,ShipVia Missing RecMoved=.
        /// </summary>
        internal static string STR_MOVED_MISSING_SHIPVIA {
            get {
                return ResourceManager.GetString("STR_MOVED_MISSING_SHIPVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL BKORD.
        /// </summary>
        internal static string STR_NLBKORD {
            get {
                return ResourceManager.GetString("STR_NLBKORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS INV.
        /// </summary>
        internal static string STR_NLINV {
            get {
                return ResourceManager.GetString("STR_NLINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS ORD.
        /// </summary>
        internal static string STR_NLORD {
            get {
                return ResourceManager.GetString("STR_NLORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records moved =.
        /// </summary>
        internal static string STR_RECORDS_MOVED {
            get {
                return ResourceManager.GetString("STR_RECORDS_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesCustomerDetailForm.
        /// </summary>
        internal static string STR_SalesCustomerDetailForm {
            get {
                return ResourceManager.GetString("STR_SalesCustomerDetailForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string STR_ShipToAddressID {
            get {
                return ResourceManager.GetString("STR_ShipToAddressID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SopCustomerDetailInquiryForm.
        /// </summary>
        internal static string STR_SopCustomerDetailInquiryForm {
            get {
                return ResourceManager.GetString("STR_SopCustomerDetailInquiryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SopEntry.
        /// </summary>
        internal static string STR_SopEntryForm {
            get {
                return ResourceManager.GetString("STR_SopEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SopInquiry.
        /// </summary>
        internal static string STR_SopInquiryForm {
            get {
                return ResourceManager.GetString("STR_SopInquiryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesItemDetailEntry.
        /// </summary>
        internal static string STR_SopItemDetailForm {
            get {
                return ResourceManager.GetString("STR_SopItemDetailForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Item Inquiry.
        /// </summary>
        internal static string STR_SopItemInquiryForm {
            get {
                return ResourceManager.GetString("STR_SopItemInquiryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string STR_SopItemProductInfo {
            get {
                return ResourceManager.GetString("STR_SopItemProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string STR_SopItemQuoteInfo {
            get {
                return ResourceManager.GetString("STR_SopItemQuoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        internal static string STR_SopItemShipmentInfo {
            get {
                return ResourceManager.GetString("STR_SopItemShipmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        internal static string STR_Source {
            get {
                return ResourceManager.GetString("STR_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR_TaxRegNo.
        /// </summary>
        internal static string STR_TaxRegNo {
            get {
                return ResourceManager.GetString("STR_TaxRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxScheduleID.
        /// </summary>
        internal static string STR_TaxScheduleID {
            get {
                return ResourceManager.GetString("STR_TaxScheduleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Issues.
        /// </summary>
        internal static string STR_VATISSUES {
            get {
                return ResourceManager.GetString("STR_VATISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string STR_VIEW {
            get {
                return ResourceManager.GetString("STR_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void.
        /// </summary>
        internal static string STR_Voided {
            get {
                return ResourceManager.GetString("STR_Voided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarehouseInstructionID.
        /// </summary>
        internal static string STR_WarehouseInstructionID {
            get {
                return ResourceManager.GetString("STR_WarehouseInstructionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Cancel {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Clear {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Copy {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Delete {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_DeleteAll {
            get {
                object obj = ResourceManager.GetObject("Toolbar_DeleteAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_New {
            get {
                object obj = ResourceManager.GetObject("Toolbar_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Open {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Post {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Print {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Redisplay {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Redisplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Save {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Void {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Void", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULK.
        /// </summary>
        internal static string UOFM_BULK {
            get {
                return ResourceManager.GetString("UOFM_BULK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_First {
            get {
                object obj = ResourceManager.GetObject("VCR_First", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Last {
            get {
                object obj = ResourceManager.GetObject("VCR_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Next {
            get {
                object obj = ResourceManager.GetObject("VCR_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Previous {
            get {
                object obj = ResourceManager.GetObject("VCR_Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Window_NoteAbsent {
            get {
                object obj = ResourceManager.GetObject("Window_NoteAbsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Window_NotePresent {
            get {
                object obj = ResourceManager.GetObject("Window_NotePresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
