//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemPoint.GP.PM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemPoint.GP.PM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EUCompanyId {
            get {
                return ResourceManager.GetString("EUCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Delete {
            get {
                object obj = ResourceManager.GetObject("Field_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Edit {
            get {
                object obj = ResourceManager.GetObject("Field_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Expansion {
            get {
                object obj = ResourceManager.GetObject("Field_Expansion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Lookup {
            get {
                object obj = ResourceManager.GetObject("Field_Lookup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_MapPoint {
            get {
                object obj = ResourceManager.GetObject("Field_MapPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_NoteAbsent {
            get {
                object obj = ResourceManager.GetObject("Field_NoteAbsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_NotePresent {
            get {
                object obj = ResourceManager.GetObject("Field_NotePresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpImage {
            get {
                object obj = ResourceManager.GetObject("HelpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NACompanyId {
            get {
                return ResourceManager.GetString("NACompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RetryCount {
            get {
                return ResourceManager.GetString("RetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string STR_AllScroll {
            get {
                return ResourceManager.GetString("STR_AllScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIDocumentsWithManualPayments.
        /// </summary>
        internal static string STR_APIDocumentsWithManualPayments {
            get {
                return ResourceManager.GetString("STR_APIDocumentsWithManualPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIId.
        /// </summary>
        internal static string STR_APIId {
            get {
                return ResourceManager.GetString("STR_APIId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Id does not exits. Please enter a correct value..
        /// </summary>
        internal static string STR_APIIdDoesNotExists {
            get {
                return ResourceManager.GetString("STR_APIIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISAPILOGENABLED.
        /// </summary>
        internal static string STR_ApiLogEnabled {
            get {
                return ResourceManager.GetString("STR_ApiLogEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APILOGFILENAME.
        /// </summary>
        internal static string STR_ApiLogFileName {
            get {
                return ResourceManager.GetString("STR_ApiLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APILOGFILEPATH.
        /// </summary>
        internal static string STR_ApiLogFilePath {
            get {
                return ResourceManager.GetString("STR_ApiLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully linked the manual payment numbers to failed Api Id(s)..
        /// </summary>
        internal static string STR_ApiManualPaymentUpdateSuccess {
            get {
                return ResourceManager.GetString("STR_ApiManualPaymentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APINonPOReUploadDocumentsSelectScroll.
        /// </summary>
        internal static string STR_APINonPOReUploadDocumentsSelectScroll {
            get {
                return ResourceManager.GetString("STR_APINonPOReUploadDocumentsSelectScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APINonPOValidDocumentsScroll.
        /// </summary>
        internal static string STR_APINonPOValidDocumentsScroll {
            get {
                return ResourceManager.GetString("STR_APINonPOValidDocumentsScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIPOReUploadDocumentsSelectScroll.
        /// </summary>
        internal static string STR_APIPOReUploadDocumentsSelectScroll {
            get {
                return ResourceManager.GetString("STR_APIPOReUploadDocumentsSelectScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIPOValidDocumentsScroll.
        /// </summary>
        internal static string STR_APIPOValidDocumentsScroll {
            get {
                return ResourceManager.GetString("STR_APIPOValidDocumentsScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string STR_APIStatusFail {
            get {
                return ResourceManager.GetString("STR_APIStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessGroupName.
        /// </summary>
        internal static string STR_BusinessGroupName {
            get {
                return ResourceManager.GetString("STR_BusinessGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessGroupName does not exists in vlookup table. Please enter a correct value..
        /// </summary>
        internal static string STR_BusinessGroupNameDoesNotExists {
            get {
                return ResourceManager.GetString("STR_BusinessGroupNameDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnitName.
        /// </summary>
        internal static string STR_BusinessUnitName {
            get {
                return ResourceManager.GetString("STR_BusinessUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessUnitName does not exists in vlookup table. Please enter a correct value..
        /// </summary>
        internal static string STR_BusinessUnitNameDoesNotExists {
            get {
                return ResourceManager.GetString("STR_BusinessUnitNameDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHMPT.
        /// </summary>
        internal static string STR_ChmptCompany {
            get {
                return ResourceManager.GetString("STR_ChmptCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPEUR.
        /// </summary>
        internal static string STR_CPEURCompany {
            get {
                return ResourceManager.GetString("STR_CPEURCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTSIDocumentsWithManualPayments.
        /// </summary>
        internal static string STR_CTSIDocumentsWithManualPayments {
            get {
                return ResourceManager.GetString("STR_CTSIDocumentsWithManualPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTSIId.
        /// </summary>
        internal static string STR_CTSIId {
            get {
                return ResourceManager.GetString("STR_CTSIId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtsiId does not exits. Please enter a correct value..
        /// </summary>
        internal static string STR_CTSIIdDoesNotExists {
            get {
                return ResourceManager.GetString("STR_CTSIIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCTSILOGENABLED.
        /// </summary>
        internal static string STR_CtsiLogEnabled {
            get {
                return ResourceManager.GetString("STR_CtsiLogEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTSILOGFILENAME.
        /// </summary>
        internal static string STR_CtsiLogFileName {
            get {
                return ResourceManager.GetString("STR_CtsiLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully linked the manual payment numbers to failed ctsi Id(s)..
        /// </summary>
        internal static string STR_CtsiManualPaymentUpdateSuccess {
            get {
                return ResourceManager.GetString("STR_CtsiManualPaymentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtsiReUploadSelectDocumentsScroll.
        /// </summary>
        internal static string STR_CTSIReUploadSelectDocumentsScroll {
            get {
                return ResourceManager.GetString("STR_CTSIReUploadSelectDocumentsScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtsiValidDocumentsScroll.
        /// </summary>
        internal static string STR_CTSIReUploadValidDocumentsScroll {
            get {
                return ResourceManager.GetString("STR_CTSIReUploadValidDocumentsScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTSIReportUploadDocumentsScroll.
        /// </summary>
        internal static string STR_CTSISelectDocumentsScroll {
            get {
                return ResourceManager.GetString("STR_CTSISelectDocumentsScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string STR_CTSIStatusFail {
            get {
                return ResourceManager.GetString("STR_CTSIStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTSIValidDocumentsScroll.
        /// </summary>
        internal static string STR_CTSIValidScroll {
            get {
                return ResourceManager.GetString("STR_CTSIValidScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Data\\Dex.ini.
        /// </summary>
        internal static string STR_DirectoryPath {
            get {
                return ResourceManager.GetString("STR_DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more VoucherNumber is already generated by some other user. Please select another document. .
        /// </summary>
        internal static string STR_DocumentAlreadyCreated {
            get {
                return ResourceManager.GetString("STR_DocumentAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Group cannot be empty. Please enter a Business Group..
        /// </summary>
        internal static string STR_EmptyBusinessGroup {
            get {
                return ResourceManager.GetString("STR_EmptyBusinessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit cannot be empty. Please enter a Business Unit..
        /// </summary>
        internal static string STR_EmptyBusinessUnit {
            get {
                return ResourceManager.GetString("STR_EmptyBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code cannot be empty..
        /// </summary>
        internal static string STR_EmptyCurrencyCode {
            get {
                return ResourceManager.GetString("STR_EmptyCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date cannot be empty. Please enter a Document Date..
        /// </summary>
        internal static string STR_EmptyDocDate {
            get {
                return ResourceManager.GetString("STR_EmptyDocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number cannot be empty..
        /// </summary>
        internal static string STR_EmptyDocumentNumber {
            get {
                return ResourceManager.GetString("STR_EmptyDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense description cannot be empty. Please enter a Expense Description..
        /// </summary>
        internal static string STR_EmptyExpenseDescription {
            get {
                return ResourceManager.GetString("STR_EmptyExpenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Type Name cannot be empty. Please enter a Expense Type Name..
        /// </summary>
        internal static string STR_EmptyExpenseTypeName {
            get {
                return ResourceManager.GetString("STR_EmptyExpenseTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLAccount Number cannot be empty. Recommend user should be set value as &apos;PO-Auto&apos;..
        /// </summary>
        internal static string STR_EmptyGLAccountNumber {
            get {
                return ResourceManager.GetString("STR_EmptyGLAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more selected documents does not contain manual payment number..
        /// </summary>
        internal static string STR_EmptyManualPaymentNumber {
            get {
                return ResourceManager.GetString("STR_EmptyManualPaymentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Id cannot be empty. Please enter a vendor Id..
        /// </summary>
        internal static string STR_EmptyVendorId {
            get {
                return ResourceManager.GetString("STR_EmptyVendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Ending Date cannot be empty. Please enter a Week Ending Date..
        /// </summary>
        internal static string STR_EmptyWeekEndingDate {
            get {
                return ResourceManager.GetString("STR_EmptyWeekEndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no valid records..
        /// </summary>
        internal static string STR_ERROR_NORECORDS {
            get {
                return ResourceManager.GetString("STR_ERROR_NORECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Loading lookup values to window..
        /// </summary>
        internal static string STR_ErrorLoadingLookup {
            get {
                return ResourceManager.GetString("STR_ErrorLoadingLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in fetching failed API Dcouments..
        /// </summary>
        internal static string STR_ErrorPopulatingFailedApiDocuments {
            get {
                return ResourceManager.GetString("STR_ErrorPopulatingFailedApiDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in fetching failed CTSI Dcouments..
        /// </summary>
        internal static string STR_ErrorPopulatingFailedCtsiDocuments {
            get {
                return ResourceManager.GetString("STR_ErrorPopulatingFailedCtsiDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in fetching failed expenses..
        /// </summary>
        internal static string STR_ErrorPopulatingFailedExpenses {
            get {
                return ResourceManager.GetString("STR_ErrorPopulatingFailedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseReportId.
        /// </summary>
        internal static string STR_ExpenseReportId {
            get {
                return ResourceManager.GetString("STR_ExpenseReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseReport does not exits. Please enter a correct value..
        /// </summary>
        internal static string STR_ExpenseReportIdDoesNotExists {
            get {
                return ResourceManager.GetString("STR_ExpenseReportIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pmExpenseReportUploadForm.
        /// </summary>
        internal static string STR_ExpenseReportUploadForm {
            get {
                return ResourceManager.GetString("STR_ExpenseReportUploadForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PmExpenseReportUploadSelectDocumentsScroll.
        /// </summary>
        internal static string STR_ExpenseReportUploadSelectDocumentsScroll {
            get {
                return ResourceManager.GetString("STR_ExpenseReportUploadSelectDocumentsScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PmExpenseReportUploadValidDocumentsScroll.
        /// </summary>
        internal static string STR_ExpenseReportUploadValidScroll {
            get {
                return ResourceManager.GetString("STR_ExpenseReportUploadValidScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string STR_ExpenseStatusFail {
            get {
                return ResourceManager.GetString("STR_ExpenseStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseTypeName.
        /// </summary>
        internal static string STR_ExpenseTypeName {
            get {
                return ResourceManager.GetString("STR_ExpenseTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseTypeName does not exists in vlookup table. Please enter a correct value..
        /// </summary>
        internal static string STR_ExpenseTypeNameDoesNotExists {
            get {
                return ResourceManager.GetString("STR_ExpenseTypeNameDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the expense records failed to validate and cannot push to GP. Please verify the failed expenses and correct and push to GP from Re-Upload failed expenses..
        /// </summary>
        internal static string STR_ExpenseUploadContainsFailedRecords {
            get {
                return ResourceManager.GetString("STR_ExpenseUploadContainsFailedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values has been changed, please revalidate to verify the results..
        /// </summary>
        internal static string STR_FieldsUpdated {
            get {
                return ResourceManager.GetString("STR_FieldsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account Description cannot be empty..
        /// </summary>
        internal static string STR_GLAccountDescription {
            get {
                return ResourceManager.GetString("STR_GLAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account does not exists. Please enter a valid GL account..
        /// </summary>
        internal static string STR_GLAccountDoesNotExists {
            get {
                return ResourceManager.GetString("STR_GLAccountDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher number does not exists for the vendor. Please select a valid voucher number..
        /// </summary>
        internal static string STR_InvoiceDoesNotExists {
            get {
                return ResourceManager.GetString("STR_InvoiceDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkFailedExpenses.
        /// </summary>
        internal static string STR_LinkFailedExpenses {
            get {
                return ResourceManager.GetString("STR_LinkFailedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully linked the manual payment numbers to failed expense Id(s)..
        /// </summary>
        internal static string STR_ManualPaymentUpdateSuccess {
            get {
                return ResourceManager.GetString("STR_ManualPaymentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INV.
        /// </summary>
        internal static string STR_MESSAGE_DOCUMENTTYPE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_DOCUMENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics GP.
        /// </summary>
        internal static string STR_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid file.
        /// </summary>
        internal static string STR_MESSAGE_VALIDFILE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_VALIDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISPAYABLESLOGENABLED.
        /// </summary>
        internal static string STR_PayablesLogEnabled {
            get {
                return ResourceManager.GetString("STR_PayablesLogEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYABLESLOGFILENAME.
        /// </summary>
        internal static string STR_PayablesLogFileName {
            get {
                return ResourceManager.GetString("STR_PayablesLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYABLESLOGFILEPATH.
        /// </summary>
        internal static string STR_PayablesLogFilePath {
            get {
                return ResourceManager.GetString("STR_PayablesLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number does not exists for the vendor. Please select a valid invoice number..
        /// </summary>
        internal static string STR_POInvoiceDoesNotExists {
            get {
                return ResourceManager.GetString("STR_POInvoiceDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Line Number can be multiple of 16384. Please enter Po Line Number..
        /// </summary>
        internal static string STR_POLineNumber {
            get {
                return ResourceManager.GetString("STR_POLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Line Number can be multiple of 16384. Please enter Receipt Line Number..
        /// </summary>
        internal static string STR_ReceiptLineNumber {
            get {
                return ResourceManager.GetString("STR_ReceiptLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the required fields..
        /// </summary>
        internal static string STR_RequiredFieldsMissing {
            get {
                return ResourceManager.GetString("STR_RequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReUploadFailureApiDocuments.
        /// </summary>
        internal static string STR_ReUploadFailureApiDocuments {
            get {
                return ResourceManager.GetString("STR_ReUploadFailureApiDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReUploadFailureCtsiDocuments.
        /// </summary>
        internal static string STR_ReUploadFailureCtsiDocuments {
            get {
                return ResourceManager.GetString("STR_ReUploadFailureCtsiDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReUploadFailureExpenses.
        /// </summary>
        internal static string STR_ReUploadFailureExpenses {
            get {
                return ResourceManager.GetString("STR_ReUploadFailureExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revalidate.
        /// </summary>
        internal static string STR_Revalidate {
            get {
                return ResourceManager.GetString("STR_Revalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string STR_SearchType_All {
            get {
                return ResourceManager.GetString("STR_SearchType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiInvoiceId.
        /// </summary>
        internal static string STR_SearchType_ApiInvoiceId {
            get {
                return ResourceManager.GetString("STR_SearchType_ApiInvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtsiId.
        /// </summary>
        internal static string STR_SearchType_CtsiId {
            get {
                return ResourceManager.GetString("STR_SearchType_CtsiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string STR_SearchType_DocumentDate {
            get {
                return ResourceManager.GetString("STR_SearchType_DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Record Id.
        /// </summary>
        internal static string STR_SearchType_ExpenseRecordId {
            get {
                return ResourceManager.GetString("STR_SearchType_ExpenseRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Id.
        /// </summary>
        internal static string STR_SearchType_VendorId {
            get {
                return ResourceManager.GetString("STR_SearchType_VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an InvoiceID..
        /// </summary>
        internal static string STR_SelectApiInvoiceId {
            get {
                return ResourceManager.GetString("STR_SelectApiInvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Api Id is selected to update. Please select one or more  Api Id(s) to update manual  payment number(s)..
        /// </summary>
        internal static string STR_SelectAtLeastOneApiDoc {
            get {
                return ResourceManager.GetString("STR_SelectAtLeastOneApiDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ctsi Id is selected to update.Please select one or more  Ctsi Id(s) to update manual  payment number(s)..
        /// </summary>
        internal static string STR_SelectAtLeastOneCtsiDoc {
            get {
                return ResourceManager.GetString("STR_SelectAtLeastOneCtsiDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expense Id is selected to update.Please select one or more  expesne Id(s) to update manual  payment number(s)..
        /// </summary>
        internal static string STR_SelectAtLeastOneExpense {
            get {
                return ResourceManager.GetString("STR_SelectAtLeastOneExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectCheckBox.
        /// </summary>
        internal static string STR_SelectCheckBox {
            get {
                return ResourceManager.GetString("STR_SelectCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a CtsiId..
        /// </summary>
        internal static string STR_SelectCtsiId {
            get {
                return ResourceManager.GetString("STR_SelectCtsiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Expense Record..
        /// </summary>
        internal static string STR_SelectExpenseRecord {
            get {
                return ResourceManager.GetString("STR_SelectExpenseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file..
        /// </summary>
        internal static string STR_SELECTFILE {
            get {
                return ResourceManager.GetString("STR_SELECTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one record..
        /// </summary>
        internal static string STR_SelectRecord {
            get {
                return ResourceManager.GetString("STR_SelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some unkonwn exception.Please retry it..
        /// </summary>
        internal static string STR_UnknownException {
            get {
                return ResourceManager.GetString("STR_UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Id does not exists. Please enter a valid vendor Id..
        /// </summary>
        internal static string STR_VendorIdDoesNotExists {
            get {
                return ResourceManager.GetString("STR_VendorIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number cannot be 0. Please enter Account Number..
        /// </summary>
        internal static string STR_ZeroAccountNumber {
            get {
                return ResourceManager.GetString("STR_ZeroAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Amount cannot be 0. Please enter approved amount  &gt; 0..
        /// </summary>
        internal static string STR_ZeroApprovedAmount {
            get {
                return ResourceManager.GetString("STR_ZeroApprovedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Amount cannot be 0. Please enter document amount  &gt; 0..
        /// </summary>
        internal static string STR_ZeroDocumentAmount {
            get {
                return ResourceManager.GetString("STR_ZeroDocumentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Cancel {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Clear {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Copy {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Delete {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_DeleteAll {
            get {
                object obj = ResourceManager.GetObject("Toolbar_DeleteAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_New {
            get {
                object obj = ResourceManager.GetObject("Toolbar_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Open {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Post {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Print {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Redisplay {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Redisplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Save {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Void {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Void", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_First {
            get {
                object obj = ResourceManager.GetObject("VCR_First", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Last {
            get {
                object obj = ResourceManager.GetObject("VCR_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Next {
            get {
                object obj = ResourceManager.GetObject("VCR_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Previous {
            get {
                object obj = ResourceManager.GetObject("VCR_Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Window_NoteAbsent {
            get {
                object obj = ResourceManager.GetObject("Window_NoteAbsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Window_NotePresent {
            get {
                object obj = ResourceManager.GetObject("Window_NotePresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
