//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemPoint.GP.AccountBL.AvaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AvaService.IAvaService")]
    public interface IAvaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/DownloadCustomerTaxDetails", ReplyAction="http://tempuri.org/IAvaService/DownloadCustomerTaxDetailsResponse")]
        string DownloadCustomerTaxDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/DownloadCustomerTaxDetails", ReplyAction="http://tempuri.org/IAvaService/DownloadCustomerTaxDetailsResponse")]
        System.Threading.Tasks.Task<string> DownloadCustomerTaxDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/ProcessFailedRecords", ReplyAction="http://tempuri.org/IAvaService/ProcessFailedRecordsResponse")]
        string ProcessFailedRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/ProcessFailedRecords", ReplyAction="http://tempuri.org/IAvaService/ProcessFailedRecordsResponse")]
        System.Threading.Tasks.Task<string> ProcessFailedRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/PushCustomerIntoAvalara", ReplyAction="http://tempuri.org/IAvaService/PushCustomerIntoAvalaraResponse")]
        ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraResponse PushCustomerIntoAvalara(ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/PushCustomerIntoAvalara", ReplyAction="http://tempuri.org/IAvaService/PushCustomerIntoAvalaraResponse")]
        System.Threading.Tasks.Task<ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraResponse> PushCustomerIntoAvalaraAsync(ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/SendCertRequestToAvalara", ReplyAction="http://tempuri.org/IAvaService/SendCertRequestToAvalaraResponse")]
        ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraResponse SendCertRequestToAvalara(ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvaService/SendCertRequestToAvalara", ReplyAction="http://tempuri.org/IAvaService/SendCertRequestToAvalaraResponse")]
        System.Threading.Tasks.Task<ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraResponse> SendCertRequestToAvalaraAsync(ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushCustomerIntoAvalara", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushCustomerIntoAvalaraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, string> customerDetails;
        
        public PushCustomerIntoAvalaraRequest() {
        }
        
        public PushCustomerIntoAvalaraRequest(System.Collections.Generic.Dictionary<string, string> customerDetails) {
            this.customerDetails = customerDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushCustomerIntoAvalaraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushCustomerIntoAvalaraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushCustomerIntoAvalaraResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logFileMessage;
        
        public PushCustomerIntoAvalaraResponse() {
        }
        
        public PushCustomerIntoAvalaraResponse(bool PushCustomerIntoAvalaraResult, string logFileMessage) {
            this.PushCustomerIntoAvalaraResult = PushCustomerIntoAvalaraResult;
            this.logFileMessage = logFileMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendCertRequestToAvalara", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendCertRequestToAvalaraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, string> certificateDetails;
        
        public SendCertRequestToAvalaraRequest() {
        }
        
        public SendCertRequestToAvalaraRequest(System.Collections.Generic.Dictionary<string, string> certificateDetails) {
            this.certificateDetails = certificateDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendCertRequestToAvalaraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendCertRequestToAvalaraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendCertRequestToAvalaraResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logFileMessage;
        
        public SendCertRequestToAvalaraResponse() {
        }
        
        public SendCertRequestToAvalaraResponse(bool SendCertRequestToAvalaraResult, string logFileMessage) {
            this.SendCertRequestToAvalaraResult = SendCertRequestToAvalaraResult;
            this.logFileMessage = logFileMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAvaServiceChannel : ChemPoint.GP.AccountBL.AvaService.IAvaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AvaServiceClient : System.ServiceModel.ClientBase<ChemPoint.GP.AccountBL.AvaService.IAvaService>, ChemPoint.GP.AccountBL.AvaService.IAvaService {
        
        public AvaServiceClient() {
        }
        
        public AvaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AvaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AvaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AvaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DownloadCustomerTaxDetails() {
            return base.Channel.DownloadCustomerTaxDetails();
        }
        
        public System.Threading.Tasks.Task<string> DownloadCustomerTaxDetailsAsync() {
            return base.Channel.DownloadCustomerTaxDetailsAsync();
        }
        
        public string ProcessFailedRecords() {
            return base.Channel.ProcessFailedRecords();
        }
        
        public System.Threading.Tasks.Task<string> ProcessFailedRecordsAsync() {
            return base.Channel.ProcessFailedRecordsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraResponse ChemPoint.GP.AccountBL.AvaService.IAvaService.PushCustomerIntoAvalara(ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraRequest request) {
            return base.Channel.PushCustomerIntoAvalara(request);
        }
        
        public bool PushCustomerIntoAvalara(System.Collections.Generic.Dictionary<string, string> customerDetails, out string logFileMessage) {
            ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraRequest inValue = new ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraRequest();
            inValue.customerDetails = customerDetails;
            ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraResponse retVal = ((ChemPoint.GP.AccountBL.AvaService.IAvaService)(this)).PushCustomerIntoAvalara(inValue);
            logFileMessage = retVal.logFileMessage;
            return retVal.PushCustomerIntoAvalaraResult;
        }
        
        public System.Threading.Tasks.Task<ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraResponse> PushCustomerIntoAvalaraAsync(ChemPoint.GP.AccountBL.AvaService.PushCustomerIntoAvalaraRequest request) {
            return base.Channel.PushCustomerIntoAvalaraAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraResponse ChemPoint.GP.AccountBL.AvaService.IAvaService.SendCertRequestToAvalara(ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraRequest request) {
            return base.Channel.SendCertRequestToAvalara(request);
        }
        
        public bool SendCertRequestToAvalara(System.Collections.Generic.Dictionary<string, string> certificateDetails, out string logFileMessage) {
            ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraRequest inValue = new ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraRequest();
            inValue.certificateDetails = certificateDetails;
            ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraResponse retVal = ((ChemPoint.GP.AccountBL.AvaService.IAvaService)(this)).SendCertRequestToAvalara(inValue);
            logFileMessage = retVal.logFileMessage;
            return retVal.SendCertRequestToAvalaraResult;
        }
        
        public System.Threading.Tasks.Task<ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraResponse> SendCertRequestToAvalaraAsync(ChemPoint.GP.AccountBL.AvaService.SendCertRequestToAvalaraRequest request) {
            return base.Channel.SendCertRequestToAvalaraAsync(request);
        }
    }
}
