//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemPoint.GP.OrderPostingBL.ReportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportServiceReference.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllUnpostedOrder", ReplyAction="http://tempuri.org/IReportService/GetAllUnpostedOrderResponse")]
        string GetAllUnpostedOrder(string Region, string BatchNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAllUnpostedOrder", ReplyAction="http://tempuri.org/IReportService/GetAllUnpostedOrderResponse")]
        System.Threading.Tasks.Task<string> GetAllUnpostedOrderAsync(string Region, string BatchNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : ChemPoint.GP.OrderPostingBL.ReportServiceReference.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<ChemPoint.GP.OrderPostingBL.ReportServiceReference.IReportService>, ChemPoint.GP.OrderPostingBL.ReportServiceReference.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllUnpostedOrder(string Region, string BatchNo) {
            return base.Channel.GetAllUnpostedOrder(Region, BatchNo);
        }
        
        public System.Threading.Tasks.Task<string> GetAllUnpostedOrderAsync(string Region, string BatchNo) {
            return base.Channel.GetAllUnpostedOrderAsync(Region, BatchNo);
        }
    }
}
