//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemPoint.GP.SalesOrderBL.PTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PTService.IPickTicketService")]
    public interface IPickTicketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickTicketService/GeneratePickTicket", ReplyAction="http://tempuri.org/IPickTicketService/GeneratePickTicketResponse")]
        string GeneratePickTicket(string invNumber, string sopNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickTicketService/GeneratePickTicket", ReplyAction="http://tempuri.org/IPickTicketService/GeneratePickTicketResponse")]
        System.Threading.Tasks.Task<string> GeneratePickTicketAsync(string invNumber, string sopNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPickTicketServiceChannel : ChemPoint.GP.SalesOrderBL.PTService.IPickTicketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PickTicketServiceClient : System.ServiceModel.ClientBase<ChemPoint.GP.SalesOrderBL.PTService.IPickTicketService>, ChemPoint.GP.SalesOrderBL.PTService.IPickTicketService {
        
        public PickTicketServiceClient() {
        }
        
        public PickTicketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PickTicketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PickTicketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PickTicketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GeneratePickTicket(string invNumber, string sopNumber) {
            return base.Channel.GeneratePickTicket(invNumber, sopNumber);
        }
        
        public System.Threading.Tasks.Task<string> GeneratePickTicketAsync(string invNumber, string sopNumber) {
            return base.Channel.GeneratePickTicketAsync(invNumber, sopNumber);
        }
    }
}
