//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chempoint.GP.RM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chempoint.GP.RM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Delete {
            get {
                object obj = ResourceManager.GetObject("Field_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Edit {
            get {
                object obj = ResourceManager.GetObject("Field_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Expansion {
            get {
                object obj = ResourceManager.GetObject("Field_Expansion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_Lookup {
            get {
                object obj = ResourceManager.GetObject("Field_Lookup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_MapPoint {
            get {
                object obj = ResourceManager.GetObject("Field_MapPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_NoteAbsent {
            get {
                object obj = ResourceManager.GetObject("Field_NoteAbsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Field_NotePresent {
            get {
                object obj = ResourceManager.GetObject("Field_NotePresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpImage {
            get {
                object obj = ResourceManager.GetObject("HelpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Value.
        /// </summary>
        internal static string STR_CREDIT_VALUE {
            get {
                return ResourceManager.GetString("STR_CREDIT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerMappingEntry.
        /// </summary>
        internal static string STR_CustomerMappingWindow {
            get {
                return ResourceManager.GetString("STR_CustomerMappingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerRemittanceEntry.
        /// </summary>
        internal static string STR_CustomerRemittanceEntry {
            get {
                return ResourceManager.GetString("STR_CustomerRemittanceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerRemittanceInquiry.
        /// </summary>
        internal static string STR_CustomerRemittanceInquiry {
            get {
                return ResourceManager.GetString("STR_CustomerRemittanceInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Value.
        /// </summary>
        internal static string STR_DEBIT_VALUE {
            get {
                return ResourceManager.GetString("STR_DEBIT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentRemittanceWindow.
        /// </summary>
        internal static string STR_EFTPaymentRemittanceWindow {
            get {
                return ResourceManager.GetString("STR_EFTPaymentRemittanceWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailRemittanceEntry.
        /// </summary>
        internal static string STR_EmailRemittanceEntry {
            get {
                return ResourceManager.GetString("STR_EmailRemittanceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailRemittanceEntryScroll.
        /// </summary>
        internal static string STR_EmailRemittanceEntryScroll {
            get {
                return ResourceManager.GetString("STR_EmailRemittanceEntryScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailRemittanceInquiry.
        /// </summary>
        internal static string STR_EmailRemittanceInquiry {
            get {
                return ResourceManager.GetString("STR_EmailRemittanceInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter invoice number..
        /// </summary>
        internal static string STR_ENER_INVOICENMBR {
            get {
                return ResourceManager.GetString("STR_ENER_INVOICENMBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount is exceed than linked amount. Please update it through Apply To Open Orders Window..
        /// </summary>
        internal static string STR_ERROR_ALREADY_APPLIED_AMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_ALREADY_APPLIED_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount is exceed than already applied amount for other document number. Please update it through Apply To Open Orders Window..
        /// </summary>
        internal static string STR_ERROR_ALREADY_APPLIED_TRX_AMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_ALREADY_APPLIED_TRX_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more documents are already saved by another user. Please select different document..
        /// </summary>
        internal static string STR_ERROR_ALREADYSAVED {
            get {
                return ResourceManager.GetString("STR_ERROR_ALREADYSAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more lines having zero applied amount. Please enter applied amount..
        /// </summary>
        internal static string STR_ERROR_AMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount is applied with this document for currency.
        /// </summary>
        internal static string STR_ERROR_APPLIED_CURRENCY {
            get {
                return ResourceManager.GetString("STR_ERROR_APPLIED_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document number is already linked. Please update it through Apply Sales Document window..
        /// </summary>
        internal static string STR_ERROR_APPLIED_TRX {
            get {
                return ResourceManager.GetString("STR_ERROR_APPLIED_TRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details field..
        /// </summary>
        internal static string STR_ERROR_DETAILS {
            get {
                return ResourceManager.GetString("STR_ERROR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Invoice Number..
        /// </summary>
        internal static string STR_ERROR_INVOICENUMBER {
            get {
                return ResourceManager.GetString("STR_ERROR_INVOICENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount should not zero to be distribute..
        /// </summary>
        internal static string STR_ERROR_REC_AMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_REC_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the required fields..
        /// </summary>
        internal static string STR_ERROR_REQUIREDFIELDS {
            get {
                return ResourceManager.GetString("STR_ERROR_REQUIREDFIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit amount is fully applied..
        /// </summary>
        internal static string STR_ERROR_SELECTAMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_SELECTAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one line..
        /// </summary>
        internal static string STR_ERROR_SELECTLINE {
            get {
                return ResourceManager.GetString("STR_ERROR_SELECTLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Type ID..
        /// </summary>
        internal static string STR_ERROR_SELECTLTYPEID {
            get {
                return ResourceManager.GetString("STR_ERROR_SELECTLTYPEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more lines having empty supportId. Please enter supportId..
        /// </summary>
        internal static string STR_ERROR_SUPPORTID {
            get {
                return ResourceManager.GetString("STR_ERROR_SUPPORTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount should not zero to be apply..
        /// </summary>
        internal static string STR_ERROR_TRX_AMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_TRX_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unapplied amount should not less than zero..
        /// </summary>
        internal static string STR_ERROR_UNAPPLIED_AMOUNT {
            get {
                return ResourceManager.GetString("STR_ERROR_UNAPPLIED_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window will be available for Credit Memo/Return transaction..
        /// </summary>
        internal static string STR_ERROR_VALIDCashDocType {
            get {
                return ResourceManager.GetString("STR_ERROR_VALIDCashDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window will be available for Credit/Debit Memo transaction..
        /// </summary>
        internal static string STR_ERROR_VALIDRMDocType {
            get {
                return ResourceManager.GetString("STR_ERROR_VALIDRMDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string STR_From {
            get {
                return ResourceManager.GetString("STR_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockBoxTransactionsForm.
        /// </summary>
        internal static string STR_LockBoxTransactionsForm {
            get {
                return ResourceManager.GetString("STR_LockBoxTransactionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics GP.
        /// </summary>
        internal static string STR_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivablesEntry.
        /// </summary>
        internal static string STR_ReceivablesEntryForm {
            get {
                return ResourceManager.GetString("STR_ReceivablesEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivablesInquiry.
        /// </summary>
        internal static string STR_ReceivablesInquiryForm {
            get {
                return ResourceManager.GetString("STR_ReceivablesInquiryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivingEntryForm.
        /// </summary>
        internal static string STR_ReceivingEntryForm {
            get {
                return ResourceManager.GetString("STR_ReceivingEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivingInquiryForm.
        /// </summary>
        internal static string STR_ReceivingInquiryForm {
            get {
                return ResourceManager.GetString("STR_ReceivingInquiryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCashReceiptForm.
        /// </summary>
        internal static string STR_RMCashReceiptForm {
            get {
                return ResourceManager.GetString("STR_RMCashReceiptForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCashReceiptInquiryForm.
        /// </summary>
        internal static string STR_RMCashReceiptinquiryForm {
            get {
                return ResourceManager.GetString("STR_RMCashReceiptinquiryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string STR_To {
            get {
                return ResourceManager.GetString("STR_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit Amount.
        /// </summary>
        internal static string STR_TOTAL_CREDIT_AMOUNT {
            get {
                return ResourceManager.GetString("STR_TOTAL_CREDIT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit Amount.
        /// </summary>
        internal static string STR_TOTAL_DEBIT_AMOUNT {
            get {
                return ResourceManager.GetString("STR_TOTAL_DEBIT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume (kgs).
        /// </summary>
        internal static string STR_VOLUME_KG {
            get {
                return ResourceManager.GetString("STR_VOLUME_KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume (lbs).
        /// </summary>
        internal static string STR_VOLUME_LB {
            get {
                return ResourceManager.GetString("STR_VOLUME_LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Cancel {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Clear {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Copy {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Delete {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_DeleteAll {
            get {
                object obj = ResourceManager.GetObject("Toolbar_DeleteAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_New {
            get {
                object obj = ResourceManager.GetObject("Toolbar_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Open {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Post {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Print {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Redisplay {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Redisplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Save {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Toolbar_Void {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Void", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_First {
            get {
                object obj = ResourceManager.GetObject("VCR_First", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Last {
            get {
                object obj = ResourceManager.GetObject("VCR_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Next {
            get {
                object obj = ResourceManager.GetObject("VCR_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VCR_Previous {
            get {
                object obj = ResourceManager.GetObject("VCR_Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Window_NoteAbsent {
            get {
                object obj = ResourceManager.GetObject("Window_NoteAbsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Window_NotePresent {
            get {
                object obj = ResourceManager.GetObject("Window_NotePresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
